/**
 * DuoSync Report Exporter
 * Supports PDF, Excel (.xlsx), and Word (.doc)
 *
 * Required packages: npm install jspdf jspdf-autotable xlsx
 */
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import * as XLSX from 'xlsx';

// ── Helper: decode username from JWT stored in localStorage ──────────────────
export const getReportUsername = () => {
  try {
    const token = localStorage.getItem('jwtToken');
    if (token) {
      const payload = JSON.parse(atob(token.split('.')[1]));
      return payload.username || payload.sub || 'Admin';
    }
    return localStorage.getItem('username') || 'Admin';
  } catch {
    return 'Admin';
  }
};

// ── Helper: build a human-readable date range string ────────────────────────
export const buildDateRangeLabel = (start, end) => {
  if (!start && !end) return 'All Time';
  if (start && !end)  return `From ${start}`;
  if (!start && end)  return `Until ${end}`;
  return `${start} to ${end}`;
};

// ── Helper: filter an array by a date field and optional date range ───────────
export const filterByDateRange = (data, dateField, startDate, endDate) => {
  if (!dateField || (!startDate && !endDate)) return data;

  const start = startDate ? new Date(`${startDate}T00:00:00`) : null;
  const end   = endDate   ? new Date(`${endDate}T23:59:59`)   : null;

  return data.filter(item => {
    const raw = item[dateField];
    if (!raw) return false;
    const d = new Date(raw);
    if (start && d < start) return false;
    if (end   && d > end)   return false;
    return true;
  });
};

// ── PDF ───────────────────────────────────────────────────────────────────────
export const exportToPDF = ({ title, columns, rows, filename, generatedBy, dateRangeLabel }) => {
  const doc = new jsPDF({ orientation: 'landscape', unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();

  // Header bar
  doc.setFillColor(30, 41, 59);
  doc.rect(0, 0, pageW, 38, 'F');

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(15);
  doc.setFont('helvetica', 'bold');
  doc.text('DuoSync Admin System', 20, 18);

  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Report: ${title}`, 20, 30);
  doc.text(
    `Generated by: ${generatedBy}   |   Period: ${dateRangeLabel}   |   ${new Date().toLocaleString()}`,
    pageW - 20, 30, { align: 'right' }
  );

  autoTable(doc, {
    startY: 46,
    head: [columns],
    body: rows,
    styles: {
      fontSize: 8,
      cellPadding: 5,
      textColor: [51, 65, 85],
      lineColor: [226, 232, 240],
      lineWidth: 0.3,
    },
    headStyles: {
      fillColor: [30, 41, 59],
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      fontSize: 8,
    },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didDrawPage: (data) => {
      const totalPages = doc.internal.getNumberOfPages();
      doc.setFontSize(7);
      doc.setTextColor(148, 163, 184);
      doc.text(
        `Page ${data.pageNumber} of ${totalPages}   |   Total records: ${rows.length}`,
        pageW / 2,
        doc.internal.pageSize.getHeight() - 10,
        { align: 'center' }
      );
    },
  });

  doc.save(`${filename}_${_stamp()}.pdf`);
};

// ── Excel ─────────────────────────────────────────────────────────────────────
export const exportToExcel = ({ title, columns, rows, filename, generatedBy, dateRangeLabel }) => {
  const meta = [
    [`DuoSync Admin System — ${title}`],
    [`Generated by: ${generatedBy}`],
    [`Period: ${dateRangeLabel}`],
    [`Generated on: ${new Date().toLocaleString()}`],
    [`Total Records: ${rows.length}`],
    [],             // blank spacer row
    columns,        // column headers
    ...rows,        // data rows
  ];

  const ws = XLSX.utils.aoa_to_sheet(meta);

  // Column width: auto-fit (approx)
  const colWidths = columns.map((_, ci) => ({
    wch: Math.max(
      columns[ci].length,
      ...rows.map(r => String(r[ci] ?? '').length)
    ) + 4,
  }));
  ws['!cols'] = colWidths;

  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, 'Report');
  XLSX.writeFile(wb, `${filename}_${_stamp()}.xlsx`);
};

// ── Word (.doc via HTML-mhtml trick — no extra package required) ──────────────
export const exportToWord = ({ title, columns, rows, filename, generatedBy, dateRangeLabel }) => {
  const escape = (str) =>
    String(str ?? '')
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;');

  const thead = columns.map(c => `<th>${escape(c)}</th>`).join('');
  const tbody = rows
    .map(row => `<tr>${row.map(cell => `<td>${escape(cell)}</td>`).join('')}</tr>`)
    .join('');

  const html = `
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
  <meta charset="UTF-8">
  <title>${escape(title)}</title>
  <style>
    body   { font-family: Arial, sans-serif; font-size: 11pt; margin: 30pt; color: #1e293b; }
    h2     { color: #0f172a; margin-bottom: 4pt; }
    .meta  { font-size: 9pt; color: #64748b; margin-bottom: 18pt; line-height: 1.8; }
    table  { width: 100%; border-collapse: collapse; margin-top: 6pt; }
    th     { background: #1e293b; color: white; padding: 7pt 8pt; text-align: left;
             font-size: 9pt; font-weight: bold; }
    td     { padding: 6pt 8pt; font-size: 9pt; border-bottom: 1pt solid #e2e8f0; }
    tr:nth-child(even) td { background: #f8fafc; }
    .footer{ font-size: 8pt; color: #94a3b8; margin-top: 14pt; }
  </style>
</head>
<body>
  <h2>DuoSync Admin System — ${escape(title)}</h2>
  <div class="meta">
    <strong>Generated by:</strong> ${escape(generatedBy)}<br>
    <strong>Period:</strong> ${escape(dateRangeLabel)}<br>
    <strong>Generated on:</strong> ${new Date().toLocaleString()}<br>
    <strong>Total Records:</strong> ${rows.length}
  </div>
  <table>
    <thead><tr>${thead}</tr></thead>
    <tbody>${tbody}</tbody>
  </table>
  <div class="footer">This document was generated automatically by DuoSync Admin System.</div>
</body>
</html>`;

  const blob = new Blob(['\ufeff', html], { type: 'application/msword' });
  const url  = URL.createObjectURL(blob);
  const a    = document.createElement('a');
  a.href     = url;
  a.download = `${filename}_${_stamp()}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

// ── Internal timestamp helper ─────────────────────────────────────────────────
const _stamp = () => {
  const d = new Date();
  return `${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}_${String(d.getHours()).padStart(2,'0')}${String(d.getMinutes()).padStart(2,'0')}`;
};